openapi: 3.0.0
info:
  title: Links API
  description: API for links microservice data exchange
  version: 0.1.0
servers:
  - url: links.juja-platform.com.ua
    description: Fictional address to specify the API server -- to be changed later
paths:
  /v1/links:
    get:
      summary: Get all links
      description: Returns a list containing saved links. The list supports paging.
      parameters:
        - in: query
          name: activeOnly
          required: true
          schema:
            type: boolean
          description: Should be active only links returned (all the links if false)
        - in: query
          name: pageSize
          schema:
            type: integer
          description: Number of links returned
        - in: query
          name: pageNumber
          schema:
            type: integer
          description: Page number
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: link`s ID at database
                    user:
                      type: string
                      description: >-
                        the user which saved the link may be shown to everyone
                        or may be not -- this field could be removed
                    url:
                      type: string
                      description: the link saved before
                    label:
                      type: string
                      description: given by user
                    reference:
                      type: string
                      description: assigned by user
                    active:
                      type: boolean
                      description: >-
                        if activeOnly == true active links should be returned
                        only, thus we may omit this field
        '404':
          description: Links not found but may be available in the future.
        5XX:
          description: Unexpected error.
    post:
      summary: Save a link
      description: Adds a new link to the links list.
      requestBody:
        description: Link to be updated
        required: true
        content:
          application/json:
            schema:
              description: >-
                A JSON object containing link`s information, has no ID before
                it`s saved, every just saved link is active by default -> no id
                & active fields
              type: object
              properties:
                user:
                  type: string
                url:
                  type: string
                label:
                  type: string
                reference:
                  type: string
      responses:
        '201':
          description: Link successfully has been saved.
          content:
            application/json:
              schema:
                description: >-
                  The user is the same, every just saved link is active by
                  default -> no user & active fields
                type: object
                properties:
                  id:
                    type: string
                    description: The link`s ID.
                  url:
                    type: string
                    description: The link user has saved.
                  label:
                    type: string
                    description: User given label
                  reference:
                    type: string
                    description: User assigned reference
        '400':
          description: Link has not been saved.
        5XX:
          description: Unexpected error.
  '/v1/links/{id}':
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: >-
          This resource represents an individual saved link. Each link is
          identified by a string 'id'
    get:
      summary: Get a link by link`s ID
      description: Returns a single link for its ID
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                required:
                  - id
                properties:
                  id:
                    type: string
                  user:
                    type: string
                  url:
                    type: string
                  label:
                    type: string
                  reference:
                    type: string
                  active:
                    type: boolean
        '401':
          description: Authorization to get access to requested data is missing or invalid.
        '404':
          description: The Link does not exist.
        5XX:
          description: Unexpected error.
    put:
      summary: Update an existing link by link`s ID
      requestBody:
        description: Link to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinksRequestBody'
      responses:
        '201':
          description: Link successfully updated.
        '400':
          description: Invalid ID supplied.
        '401':
          description: Authorization to get access to requested data is missing or invalid.
        '404':
          description: A link with the specified ID was not found.
        5XX:
          description: Unexpected error.
    delete:
      summary: Delete the link specified by it`s ID.
      responses:
        '204':
          description: Link has been deleted.
        '400':
          description: Invalid ID supplied.
        '401':
          description: Authorization to get access to requested data is missing or invalid.
        '404':
          description: A link with the specified ID was not found.
        5XX:
          description: Unexpected error.
  '/v1/links/user/{user}':
    get:
      summary: Get all user`s links by user`s ID
      description: Returns a list containing saved links. The list supports paging.
      parameters:
        - in: path
          name: user
          required: true
          description: The link's ID
          schema:
            type: string
        - in: query
          name: pageSize
          description: Number of links returned
          schema:
            type: integer
        - in: query
          name: pageNumber
          description: Page number
          schema:
            type: integer
      responses:
        '200':
          description: Links of the user.
          content:
            application/json:
              schema:
                required:
                  - user
                type: array
                items:
                  required:
                    - id
                  properties:
                    id:
                      type: string
                    user:
                      type: string
                    url:
                      type: string
                    label:
                      type: string
                    reference:
                      type: string
                    active:
                      type: boolean
        '400':
          description: Invalid ID supplied.
        '401':
          description: Authorization to get access to requested data is missing or invalid.
        '404':
          description: The user has no links.
        5XX:
          description: Unexpected error.
components:
  schemas:
    LinksRequestBody:
      description: A JSON object containing link`s information
      type: object
      properties:
        id:
          type: string
          description: link`s ID at database
        user:
          type: string
          description: the user which saved the link
        url:
          type: string
          description: the link been saved before
        label:
          type: string
          description: a label given by user
        reference:
          type: string
          description: a reference assigned by user
        active:
          type: boolean
          description: active links only are visible to the user specified
      example:
        id: 100500
        user: asdfa64839412
        url: 'https://swagger.io/docs/specification/describing-request-body/'
        label: Request body description
        reference: Open API
        active: true
