swagger: '2.0'
info:
  title: Links API
  description: 'API for links microservice data exchange.  '
  version: 0.1.0
host: evo.juja.com.ua
basePath: /v1
schemes:
  - https
produces:
  - application/json
paths:
  /links:
    get:
      summary: Get all links
      description: Returns a list containing saved links. The list supports paging.
      operationId: ''
      parameters:
        - in: query
          name: includeArchived
          type: boolean
          description: 'set true to get archived links, default value - false'
          required: false
      responses:
        '200':
          description: Ok
          schema:
            description: A JSON object containing link`s information
            type: object
            properties:
              id:
                type: string
                description: link`s ID at database
              user:
                type: string
                description: the user which saved the link
              url:
                type: string
                description: the link been saved before
              label:
                type: string
                description: a label given by user
              archived:
                type: boolean
                description: archived links are not visible to users
            example:
              id: 100500
              user: asdfa64839412
              url: 'https://swagger.io/docs/specification/describing-request-body/'
              label: Saved link's label given by user
              archived: false
        '404':
          description: Links not found but may be available in the future.
        '500':
          description: Unexpected error.
    post:
      summary: Save a link
      description: Adds a new link to the links list.
      operationId: ''
      consumes:
        - application/json
      parameters:
        - in: body
          name: link
          description: Link to be saved
          required: true
          schema:
            description: >-
              A JSON object containing link`s information, has no ID before it`s
              saved, every just saved link is not archived by default, so there
              is no id & active fields
            type: object
            properties:
              user:
                type: string
                description: the user which is saving the link
              url:
                type: string
                description: the link being saved
              label:
                type: string
                description: a label given by user
            example:
              user: asdfa64839412
              url: 'https://swagger.io/docs/specification/describing-request-body/'
              label: Saved link's label given by user
      responses:
        '201':
          description: Link successfully has been saved.
          schema:
            description: A JSON object containing link`s information
            type: object
            properties:
              id:
                type: string
                description: link`s ID at database
              user:
                type: string
                description: the user which saved the link
              url:
                type: string
                description: the link been saved before
              label:
                type: string
                description: a label given by user
              archived:
                type: boolean
                description: archived links are not visible to users
            example:
              id: 100500
              user: asdfa64839412
              url: 'https://swagger.io/docs/specification/describing-request-body/'
              label: Saved link's label given by user
              archived: false
        '400':
          description: Link has not been saved.
        '500':
          description: Unexpected error.
